config/routes.rb
Rails.application.routes.draw do

  resources :bcis
  resources :unidades
  resources :cadastros
  get 'mapa/Index'
  devise_for :users
  root :to => 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/bci.rb
class Bci < ApplicationRecord
  belongs_to :unidade
end

app/models/cadastro.rb
class Cadastro < ApplicationRecord
end

app/models/unidade.rb
class Unidade < ApplicationRecord
  belongs_to :cadastro
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!


    
end

app/controllers/bcis_controller.rb
class BcisController < ApplicationController
  before_action :set_bci, only: [:show, :edit, :update, :destroy]

  # GET /bcis
  # GET /bcis.json
  def index
    @bcis = Bci.all
  end

  # GET /bcis/1
  # GET /bcis/1.json
  def show
  end

  # GET /bcis/new
  def new
    @bci = Bci.new
  end

  # GET /bcis/1/edit
  def edit
  end

  # POST /bcis
  # POST /bcis.json
  def create
    @bci = Bci.new(bci_params)

    respond_to do |format|
      if @bci.save
        format.html { redirect_to @bci, notice: 'Bci was successfully created.' }
        format.json { render :show, status: :created, location: @bci }
      else
        format.html { render :new }
        format.json { render json: @bci.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bcis/1
  # PATCH/PUT /bcis/1.json
  def update
    respond_to do |format|
      if @bci.update(bci_params)
        format.html { redirect_to @bci, notice: 'Bci was successfully updated.' }
        format.json { render :show, status: :ok, location: @bci }
      else
        format.html { render :edit }
        format.json { render json: @bci.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bcis/1
  # DELETE /bcis/1.json
  def destroy
    @bci.destroy
    respond_to do |format|
      format.html { redirect_to bcis_url, notice: 'Bci was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bci
      @bci = Bci.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bci_params
      params.require(:bci).permit(:unidade_id, :data_cadastro, :zoneamento, :tp_patrimonio, :classe_edif, :pavimento, :padrao, :utilizacao, :material, :ano_const, :area_const, :area_lote, :test_frente, :test_direita, :test_fundos, :test_esquerda, :n_test, :area_test, :qtd_test, :profu, :sarjeta, :coleta_lixo, :agua, :esgoto, :iluminacao, :energia, :pavimentacao, :telefone, :guia, :situacao_lote, :pedologia, :urbanismo, :terreno, :nivel_rua, :ocupacao, :valor_m_terreno, :valor_venal, :valor_pvg, :descricao)
    end
end

app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
  before_action :set_cadastro, only: [:show, :edit, :update, :destroy]

  # GET /cadastros
  # GET /cadastros.json
  def index
    @cadastros = Cadastro.all
  end

  # GET /cadastros/1
  # GET /cadastros/1.json
  def show
  end

  # GET /cadastros/new
  def new
    @cadastro = Cadastro.new
  end

  # GET /cadastros/1/edit
  def edit
  end

  # POST /cadastros
  # POST /cadastros.json
  def create
    @cadastro = Cadastro.new(cadastro_params)

    respond_to do |format|
      if @cadastro.save
        format.html { redirect_to @cadastro, notice: 'Cadastro was successfully created.' }
        format.json { render :show, status: :created, location: @cadastro }
      else
        format.html { render :new }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastros/1
  # PATCH/PUT /cadastros/1.json
  def update
    respond_to do |format|
      if @cadastro.update(cadastro_params)
        format.html { redirect_to @cadastro, notice: 'Cadastro was successfully updated.' }
        format.json { render :show, status: :ok, location: @cadastro }
      else
        format.html { render :edit }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastros/1
  # DELETE /cadastros/1.json
  def destroy
    @cadastro.destroy
    respond_to do |format|
      format.html { redirect_to cadastros_url, notice: 'Cadastro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro
      @cadastro = Cadastro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cadastro_params
      params.require(:cadastro).permit(:nome, :cpf_cnpj, :rg_inscr_estadual, :cnh, :data_doc, :telefone, :estado, :cidade, :bairro, :logradouro, :cep, :numero, :complemento)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mapa_controller.rb
class MapaController < ApplicationController
  def Index
  end
end

app/controllers/unidades_controller.rb
class UnidadesController < ApplicationController
  before_action :set_unidade, only: [:show, :edit, :update, :destroy]

  # GET /unidades
  # GET /unidades.json
  def index
    @unidades = Unidade.all
  end

  # GET /unidades/1
  # GET /unidades/1.json
  def show
  end

  # GET /unidades/new
  def new
    @unidade = Unidade.new
  end

  # GET /unidades/1/edit
  def edit
  end

  # POST /unidades
  # POST /unidades.json
  def create
    @unidade = Unidade.new(unidade_params)

    respond_to do |format|
      if @unidade.save
        format.html { redirect_to @unidade, notice: 'Unidade was successfully created.' }
        format.json { render :show, status: :created, location: @unidade }
      else
        format.html { render :new }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unidades/1
  # PATCH/PUT /unidades/1.json
  def update
    respond_to do |format|
      if @unidade.update(unidade_params)
        format.html { redirect_to @unidade, notice: 'Unidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @unidade }
      else
        format.html { render :edit }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidades/1
  # DELETE /unidades/1.json
  def destroy
    @unidade.destroy
    respond_to do |format|
      format.html { redirect_to unidades_url, notice: 'Unidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unidade
      @unidade = Unidade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unidade_params
      params.require(:unidade).permit(:cadastro_id, :insc_imob, :insc_imb_anterior, :unidade, :tipo_imovel, :matricula, :cod_face, :quadra, :lote, :sub_lote, :setor, :loteamento, :zoneamento, :logradouro, :cep, :numero, :complemento, :info_complementar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bcis_helper.rb
module BcisHelper
end

app/helpers/cadastros_helper.rb
module CadastrosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mapa_helper.rb
module MapaHelper
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/views/bcis/edit.html.erb
<h1>Editing Bci</h1>

<%= render 'form', bci: @bci %>

<%= link_to 'Show', @bci %> |
<%= link_to 'Back', bcis_path %>

app/views/bcis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boletim de Cadastro Imobiliário</h1>

<div class="table-responsive">
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Unidade</th>
      <th>Data cadastro</th>
      <th>Zoneamento</th>
      <th>Tp patrimonio</th>
      <th>Classe edif</th>
      <th>Pavimento</th>
      <th>Padrao</th>
      <th>Utilizacao</th>
      <th>Material</th>
      <th>Ano const</th>
      <th>Area const</th>
      <th>Area lote</th>
      <th>Test frente</th>
      <th>Test direita</th>
      <th>Test fundos</th>
      <th>Test esquerda</th>
      <th>N test</th>
      <th>Area test</th>
      <th>Qtd test</th>
      <th>Profu</th>
      <th>Sarjeta</th>
      <th>Coleta lixo</th>
      <th>Agua</th>
      <th>Esgoto</th>
      <th>Iluminacao</th>
      <th>Energia</th>
      <th>Pavimentacao</th>
      <th>Telefone</th>
      <th>Guia</th>
      <th>Situacao lote</th>
      <th>Pedologia</th>
      <th>Urbanismo</th>
      <th>Terreno</th>
      <th>Nivel rua</th>
      <th>Ocupacao</th>
      <th>Valor m terreno</th>
      <th>Valor venal</th>
      <th>Valor pvg</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bcis.each do |bci| %>
      <tr>
        <td><%= bci.unidade_id %></td>
        <td><%= bci.data_cadastro %></td>
        <td><%= bci.zoneamento %></td>
        <td><%= bci.tp_patrimonio %></td>
        <td><%= bci.classe_edif %></td>
        <td><%= bci.pavimento %></td>
        <td><%= bci.padrao %></td>
        <td><%= bci.utilizacao %></td>
        <td><%= bci.material %></td>
        <td><%= bci.ano_const %></td>
        <td><%= bci.area_const %></td>
        <td><%= bci.area_lote %></td>
        <td><%= bci.test_frente %></td>
        <td><%= bci.test_direita %></td>
        <td><%= bci.test_fundos %></td>
        <td><%= bci.test_esquerda %></td>
        <td><%= bci.n_test %></td>
        <td><%= bci.area_test %></td>
        <td><%= bci.qtd_test %></td>
        <td><%= bci.profu %></td>
        <td><%= bci.sarjeta %></td>
        <td><%= bci.coleta_lixo %></td>
        <td><%= bci.agua %></td>
        <td><%= bci.esgoto %></td>
        <td><%= bci.iluminacao %></td>
        <td><%= bci.energia %></td>
        <td><%= bci.pavimentacao %></td>
        <td><%= bci.telefone %></td>
        <td><%= bci.guia %></td>
        <td><%= bci.situacao_lote %></td>
        <td><%= bci.pedologia %></td>
        <td><%= bci.urbanismo %></td>
        <td><%= bci.terreno %></td>
        <td><%= bci.nivel_rua %></td>
        <td><%= bci.ocupacao %></td>
        <td><%= bci.valor_m_terreno %></td>
        <td><%= bci.valor_venal %></td>
        <td><%= bci.valor_pvg %></td>
        <td><%= bci.descricao %></td>
        <td><%= link_to 'Show', bci %></td>
        <td><%= link_to 'Edit', edit_bci_path(bci) %></td>
        <td><%= link_to 'Destroy', bci, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 </div>
<br>

<%= link_to 'New Bci', new_bci_path %>

app/views/bcis/new.html.erb
<h1>New Bci</h1>

<%= render 'form', bci: @bci %>

<%= link_to 'Back', bcis_path %>

app/views/bcis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Unidade:</strong>
  <%= @bci.unidade_id %>
</p>

<p>
  <strong>Data cadastro:</strong>
  <%= @bci.data_cadastro %>
</p>

<p>
  <strong>Zoneamento:</strong>
  <%= @bci.zoneamento %>
</p>

<p>
  <strong>Tp patrimonio:</strong>
  <%= @bci.tp_patrimonio %>
</p>

<p>
  <strong>Classe edif:</strong>
  <%= @bci.classe_edif %>
</p>

<p>
  <strong>Pavimento:</strong>
  <%= @bci.pavimento %>
</p>

<p>
  <strong>Padrao:</strong>
  <%= @bci.padrao %>
</p>

<p>
  <strong>Utilizacao:</strong>
  <%= @bci.utilizacao %>
</p>

<p>
  <strong>Material:</strong>
  <%= @bci.material %>
</p>

<p>
  <strong>Ano const:</strong>
  <%= @bci.ano_const %>
</p>

<p>
  <strong>Area const:</strong>
  <%= @bci.area_const %>
</p>

<p>
  <strong>Area lote:</strong>
  <%= @bci.area_lote %>
</p>

<p>
  <strong>Test frente:</strong>
  <%= @bci.test_frente %>
</p>

<p>
  <strong>Test direita:</strong>
  <%= @bci.test_direita %>
</p>

<p>
  <strong>Test fundos:</strong>
  <%= @bci.test_fundos %>
</p>

<p>
  <strong>Test esquerda:</strong>
  <%= @bci.test_esquerda %>
</p>

<p>
  <strong>N test:</strong>
  <%= @bci.n_test %>
</p>

<p>
  <strong>Area test:</strong>
  <%= @bci.area_test %>
</p>

<p>
  <strong>Qtd test:</strong>
  <%= @bci.qtd_test %>
</p>

<p>
  <strong>Profu:</strong>
  <%= @bci.profu %>
</p>

<p>
  <strong>Sarjeta:</strong>
  <%= @bci.sarjeta %>
</p>

<p>
  <strong>Coleta lixo:</strong>
  <%= @bci.coleta_lixo %>
</p>

<p>
  <strong>Agua:</strong>
  <%= @bci.agua %>
</p>

<p>
  <strong>Esgoto:</strong>
  <%= @bci.esgoto %>
</p>

<p>
  <strong>Iluminacao:</strong>
  <%= @bci.iluminacao %>
</p>

<p>
  <strong>Energia:</strong>
  <%= @bci.energia %>
</p>

<p>
  <strong>Pavimentacao:</strong>
  <%= @bci.pavimentacao %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @bci.telefone %>
</p>

<p>
  <strong>Guia:</strong>
  <%= @bci.guia %>
</p>

<p>
  <strong>Situacao lote:</strong>
  <%= @bci.situacao_lote %>
</p>

<p>
  <strong>Pedologia:</strong>
  <%= @bci.pedologia %>
</p>

<p>
  <strong>Urbanismo:</strong>
  <%= @bci.urbanismo %>
</p>

<p>
  <strong>Terreno:</strong>
  <%= @bci.terreno %>
</p>

<p>
  <strong>Nivel rua:</strong>
  <%= @bci.nivel_rua %>
</p>

<p>
  <strong>Ocupacao:</strong>
  <%= @bci.ocupacao %>
</p>

<p>
  <strong>Valor m terreno:</strong>
  <%= @bci.valor_m_terreno %>
</p>

<p>
  <strong>Valor venal:</strong>
  <%= @bci.valor_venal %>
</p>

<p>
  <strong>Valor pvg:</strong>
  <%= @bci.valor_pvg %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @bci.descricao %>
</p>

<%= link_to 'Edit', edit_bci_path(@bci) %> |
<%= link_to 'Back', bcis_path %>

app/views/cadastros/_form.html.erb
<%= form_with(model: cadastro, local: true) do |form| %>
  <% if cadastro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cadastro.errors.count, "error") %> prohibited this cadastro from being saved:</h2>

      <ul>
        <% cadastro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cpf_cnpj %>
    <%= form.text_field :cpf_cnpj %>
  </div>

  <div class="field">
    <%= form.label :rg_inscr_estadual %>
    <%= form.text_field :rg_inscr_estadual %>
  </div>

  <div class="field">
    <%= form.label :cnh %>
    <%= form.text_field :cnh %>
  </div>

  <div class="field">
    <%= form.label :data_doc %>
    <%= form.datetime_select :data_doc %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro %>
  </div>

  <div class="field">
    <%= form.label :logradouro %>
    <%= form.text_field :logradouro %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero %>
  </div>

  <div class="field">
    <%= form.label :complemento %>
    <%= form.text_field :complemento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cadastros/edit.html.erb
<h1>Editing Cadastro</h1>

<%= render 'form', cadastro: @cadastro %>

<%= link_to 'Show', @cadastro %> |
<%= link_to 'Back', cadastros_path %>

app/views/cadastros/index.html.erb
<p id="notice"><%= notice %></p>


 <h2>Cadastros Contribuintes</h2>
<div class="table-responsive">
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Nome</th>
      <th>CPF/IE</th>
      <th>RG/IE</th>
      <th>CNH</th>
      <th>DATA DOC</th>
      <th>TELEFONE</th>
      <th>ESTADO</th>
      <th>CIDADE</th>
      <th>BAIRRO</th>
      <th>LOGRADOURO</th>
      <th>CEP</th>
      <th>NÚMERO</th>
      <th>COMPLEMENTO</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cadastros.each do |cadastro| %>
      <tr>
        <td><%= cadastro.nome %></td>
        <td><%= cadastro.cpf_cnpj %></td>
        <td><%= cadastro.rg_inscr_estadual %></td>
        <td><%= cadastro.cnh %></td>
        <td><%= cadastro.data_doc %></td>
        <td><%= cadastro.telefone %></td>
        <td><%= cadastro.estado %></td>
        <td><%= cadastro.cidade %></td>
        <td><%= cadastro.bairro %></td>
        <td><%= cadastro.logradouro %></td>
        <td><%= cadastro.cep %></td>
        <td><%= cadastro.numero %></td>
        <td><%= cadastro.complemento %></td>
        <td><%= link_to 'Ver', cadastro %></td>
        <td><%= link_to 'Editar', edit_cadastro_path(cadastro) %></td>
        <td><%= link_to 'Apagar', cadastro, method: :delete, data: { confirm: 'certeza em apagar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 </div>

<br>

app/views/cadastros/new.html.erb
<h1>New Cadastro</h1>

<%= render 'form', cadastro: @cadastro %>

<%= link_to 'Back', cadastros_path %>

app/views/cadastros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cadastro.nome %>
</p>

<p>
  <strong>Cpf cnpj:</strong>
  <%= @cadastro.cpf_cnpj %>
</p>

<p>
  <strong>Rg inscr estadual:</strong>
  <%= @cadastro.rg_inscr_estadual %>
</p>

<p>
  <strong>Cnh:</strong>
  <%= @cadastro.cnh %>
</p>

<p>
  <strong>Data doc:</strong>
  <%= @cadastro.data_doc %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cadastro.telefone %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @cadastro.estado %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @cadastro.cidade %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @cadastro.bairro %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= @cadastro.logradouro %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @cadastro.cep %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @cadastro.numero %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @cadastro.complemento %>
</p>

<%= link_to 'Edit', edit_cadastro_path(@cadastro) %> |
<%= link_to 'Back', cadastros_path %>

app/views/layouts/mapa.html.erb
        <!-- Begin Page Content -->
        <div class="container-fluid">
          <!-- Page Heading -->
           <%= yield %>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; GEOSMART 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

app/views/unidades/edit.html.erb
<h1>Editing Unidade</h1>

<%= render 'form', unidade: @unidade %>

<%= link_to 'Show', @unidade %> |
<%= link_to 'Back', unidades_path %>

app/views/unidades/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Unidades</h2>
<div class="table-responsive">
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Cadastro</th>
      <th>Insc imob</th>
      <th>Insc imb anterior</th>
      <th>Unidade</th>
      <th>Tipo imovel</th>
      <th>Matricula</th>
      <th>Cod face</th>
      <th>Quadra</th>
      <th>Lote</th>
      <th>Sub lote</th>
      <th>Setor</th>
      <th>Loteamento</th>
      <th>Zoneamento</th>
      <th>Logradouro</th>
      <th>Cep</th>
      <th>Numero</th>
      <th>Complemento</th>
      <th>Info complementar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unidades.each do |unidade| %>
      <tr>
        <td><%= unidade.cadastro_id %></td>
        <td><%= unidade.insc_imob %></td>
        <td><%= unidade.insc_imb_anterior %></td>
        <td><%= unidade.unidade %></td>
        <td><%= unidade.tipo_imovel %></td>
        <td><%= unidade.matricula %></td>
        <td><%= unidade.cod_face %></td>
        <td><%= unidade.quadra %></td>
        <td><%= unidade.lote %></td>
        <td><%= unidade.sub_lote %></td>
        <td><%= unidade.setor %></td>
        <td><%= unidade.loteamento %></td>
        <td><%= unidade.zoneamento %></td>
        <td><%= unidade.logradouro %></td>
        <td><%= unidade.cep %></td>
        <td><%= unidade.numero %></td>
        <td><%= unidade.complemento %></td>
        <td><%= unidade.info_complementar %></td>
        <td><%= link_to 'Show', unidade %></td>
        <td><%= link_to 'Edit', edit_unidade_path(unidade) %></td>
        <td><%= link_to 'Destroy', unidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<br>

<%= link_to 'New Unidade', new_unidade_path %>

app/views/unidades/new.html.erb
<h1>New Unidade</h1>

<%= render 'form', unidade: @unidade %>

<%= link_to 'Back', unidades_path %>

app/views/unidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cadastro:</strong>
  <%= @unidade.cadastro_id %>
</p>

<p>
  <strong>Insc imob:</strong>
  <%= @unidade.insc_imob %>
</p>

<p>
  <strong>Insc imb anterior:</strong>
  <%= @unidade.insc_imb_anterior %>
</p>

<p>
  <strong>Unidade:</strong>
  <%= @unidade.unidade %>
</p>

<p>
  <strong>Tipo imovel:</strong>
  <%= @unidade.tipo_imovel %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @unidade.matricula %>
</p>

<p>
  <strong>Cod face:</strong>
  <%= @unidade.cod_face %>
</p>

<p>
  <strong>Quadra:</strong>
  <%= @unidade.quadra %>
</p>

<p>
  <strong>Lote:</strong>
  <%= @unidade.lote %>
</p>

<p>
  <strong>Sub lote:</strong>
  <%= @unidade.sub_lote %>
</p>

<p>
  <strong>Setor:</strong>
  <%= @unidade.setor %>
</p>

<p>
  <strong>Loteamento:</strong>
  <%= @unidade.loteamento %>
</p>

<p>
  <strong>Zoneamento:</strong>
  <%= @unidade.zoneamento %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= @unidade.logradouro %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @unidade.cep %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @unidade.numero %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @unidade.complemento %>
</p>

<p>
  <strong>Info complementar:</strong>
  <%= @unidade.info_complementar %>
</p>

<%= link_to 'Edit', edit_unidade_path(@unidade) %> |
<%= link_to 'Back', unidades_path %>